# Generated by Django 5.0.2 on 2024-02-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del proyecto')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='portafolio/images/', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
        ),
    ]
